name: Docker Image CI

on:
  push:
    branches:
      - "release/*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set VERSION env
        run: |
          VERSION="${GITHUB_REF_NAME#*/}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Set IMAGE env (lowercase for GHCR)
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER,,}"
          REPO="${GITHUB_REPOSITORY#*/}"
          REPO="${REPO,,}"
          echo "OWNER=$OWNER" >> "$GITHUB_ENV"
          echo "REPO=$REPO" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            NEXT_PUBLIC_VERSION=${{ env.VERSION }}
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/naver/${{ github.event.repository.name }}:v${{ env.VERSION }}
            ${{ secrets.HARBOR_REGISTRY }}/naver/${{ github.event.repository.name }}:latest
            ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:v${{ env.VERSION }}
            ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest
            

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Trigger GitLab deploy pipeline
      #   shell: bash
      #   run: |
      #     set +x
      #     curl -sS -X POST \
      #       -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
      #       -F "ref=main" \
      #       "${{ secrets.GITLAB_TRIGGER_URL }}" \
      #       > /dev/null 2>&1
      - name: Webhook deploy
        shell: bash
        run: |
          set +x
          curl -sS -X POST \
          -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}" \
          -H "X-Target-Service: ${{ secrets.TARGET_SERVICE }}" \
          -H "X-Target-Path: ${{ secrets.TARGET_SERVICE_PATH }}" \
          "${{ secrets.WEBHOOK_URL }}" \
          > /dev/null 2>&1
