name: Docker Image CI

on:
  push:
    branches:
      - release/*
env:
  VERSION: $(echo ${{ github.ref_name }} | cut -f2 -d'/')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set VERSION env
        run: echo "VERSION=${GITHUB_REF_NAME#*/}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci --include=optional

      - name: Build project
        run: NEXT_PUBLIC_VERSION=${GITHUB_REF_NAME#*/} \
          npm run build

      - uses: docker/setup-buildx-action@v3.3.0

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/naver/${{ github.event.repository.name }}:v${{ env.VERSION }}
            ${{ secrets.HARBOR_REGISTRY }}/naver/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
